/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myTwitter;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import twitter4j.ResponseList;
import twitter4j.Status;

/**
 *
 * @author wbarahona
 */
public class myTwitter extends javax.swing.JFrame {
    DefaultListModel list = new DefaultListModel();
    /** 
     * Creates new form myTwitter
     */
    public myTwitter() {
        initComponents();
        myTwitterCore TWCoreBase = new myTwitterCore();
        try{
            ResponseList var = TWCoreBase.loadTL();
            
            
            for (Object each : var)
            {
                 Status s = (Status) each;
                 //System.out.println("Sent by: @" + s.getUser().getScreenName()+ " - " + s.getUser().getName() + "\n" + s.getText()+ "\n");
                 
                 list.addElement("@"+s.getUser().getScreenName()+ " - " + s.getUser().getName() + "\n" + s.getText()+ "\n\n\n");
                 TLlist.setModel(list);
            }
            
        }
        catch(Exception exception){
            JOptionPane.showMessageDialog(null, "Whoa there Tex! "+exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TweetText = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TLlist = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        TweetText.setToolTipText("");

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Tweet");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(TLlist);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, TweetText)
                    .add(layout.createSequentialGroup()
                        .add(0, 917, Short.MAX_VALUE)
                        .add(jToggleButton1))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TweetText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
        myTwitterCore TWCoreBase = new myTwitterCore();
        
        
        try{
            ResponseList var = TWCoreBase.tweetaction(TweetText.getText());
            
            
            for (Object each : var)
            {
                 Status s = (Status) each;
                 //System.out.println("Sent by: @" + s.getUser().getScreenName()+ " - " + s.getUser().getName() + "\n" + s.getText()+ "\n");
                 
                 list.addElement("@"+s.getUser().getScreenName()+ " - " + s.getUser().getName() + "\n" + s.getText()+ "\n\n\n");
                 TLlist.setModel(list);
            }
            
        }
        catch(Exception exception){
            JOptionPane.showMessageDialog(null, "Whoa there Tex! "+exception);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                    
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myTwitter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList TLlist;
    private javax.swing.JTextField TweetText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
